
feign.httpclient.enabled: true
feign.okhttp.enabled: true

feign:
  client:
    post:
      baseUrl: http://localhost:8082
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
